name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Specify windows-latest to run on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Set up Gradle
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Build with Gradle
        env:
          ORG_GRADLE_PROJECT_jdkPath: C:\Program Files\Java\jdk-17
        run: |
          ./gradlew build --no-daemon -Dorg.gradle.java.home="${ORG_GRADLE_PROJECT_jdkPath}"


      - name: Run tests
        run: ./gradlew test
