name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Specify windows-latest to run on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Specify the Java version you need
          distribution: 'adopt'  # Specify the Java distribution
          java-package: 'jdk'
          architecture: 'x64'
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true
          job-status: 'success'  # Optionally specify job status

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test

